language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
    - platformio update
    - platformio lib install

before_script:
    - cp .travis.config.h src/config.h

script:
    - platformio run
    - cp .travis.config-mqtt.h src/config.h
    - platformio run
